# personally i find it convenient to keep this resolver updated to pandoc's
resolver: lts-12.6

# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#  subdirs:
#  - auto-update
#  - wai
#
# A package marked 'extra-dep: true' will only be built if demanded by a
# non-dependency (i.e. a user package), and its test suites and benchmarks
# will not be run. This is useful for tweaking upstream packages.
# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)

# vedi https://stackoverflow.com/questions/35491660/can-i-automatically-embed-pandocs-default-templates-in-my-application e https://github.com/italia/docs-italia-comandi-conversione/issues/35#issuecomment-401947775

extra-deps:
- archive: https://github.com/italia/pandoc/archive/dbd86f135855074e108141548c02f0091733904e.zip
- file-embed-0.0.10
- haddock-library-1.6.0
- HsYAML-0.1.1.1

flags:
 pandoc:
  embed_data_files: true

packages:
- .

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.6"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor